#!/usr/bin/env bash
# AWS CloudFormation Defaults

# Defaults
process_cfn(){
  local stack A P T
  stack="${1:-}"

  # Default command arguments
  A=''

  # Common paramaters
  P="'ParameterKey=EnvType,ParameterValue=${ENVTYPE}'"

  # Common tags
  T="     'Key=Group,Value=${AWS_TAG_GROUP}'"
  T="${T} 'Key=Project,Value=${AWS_TAG_PROJECT}'"

  # Other
  export depends_on=

  # Stack defaults
  case "$stack" in
    billing)
      name='BillingAlarms'
      body='billing.yml'
      P="${P} 'ParameterKey=LowMonthlyExpense,ParameterValue=$((AWS_BUDGET/3))'"
      P="${P} 'ParameterKey=MedMonthlyExpense,ParameterValue=$((AWS_BUDGET/2))'"
      P="${P} 'ParameterKey=MaxMonthlyExpense,ParameterValue=${AWS_BUDGET}'"
      P="${P} 'ParameterKey=RecipientEmailAddress,ParameterValue=${NOTIFICATION_EMAIL}'"
      ;;
    cloudtrail)
      name='CloudTrail'
      A='--capabilities CAPABILITY_NAMED_IAM'
      P="${P} 'ParameterKey=CloudWatchLogsRetentionInDays,ParameterValue=${AWS_LOG_RETENTION_DAYS}'"
      ;;
    docker_cloud)
      export AWS_PROFILE='default'
      name='DockerCloud'
      body='docker_cloud.yml'
      A='--capabilities CAPABILITY_NAMED_IAM'
      ;;
    notifications)
      name='Notifications'
      body='notifications.yml'
      P="${P} 'ParameterKey=NotificationEmail,ParameterValue=${NOTIFICATION_EMAIL}'"
      ;;
    prometheus)
      export AWS_PROFILE='aws2017a'
      export AWS_EC2_KEY='vgh'
      name='Prometheus'
      body='prometheus/main.yml'
      depends_on='prometheus-iam,prometheus-sg'
      P="${P} 'ParameterKey=KeyName,ParameterValue=${AWS_EC2_KEY}'"
      P="${P} 'ParameterKey=ImageID,ParameterValue=ami-3dec9947'"
      # P="${P} 'ParameterKey=ImageID,ParameterValue=\"$(vgs_aws_ec2_get_ubuntu_official_ami_id)\"'"
      P="${P} 'ParameterKey=InstanceType,ParameterValue=t2.micro'"
      ;;
    prometheus-iam)
      export AWS_PROFILE='aws2017a'
      name='PrometheusIAM'
      body='prometheus/iam.yml'
      A='--capabilities CAPABILITY_NAMED_IAM'
      P="${P} 'ParameterKey=AssetsBucket,ParameterValue=${PROMETHEUS_ASSETS_BUCKET}'"
      ;;
    prometheus-sg)
      export AWS_PROFILE='aws2017a'
      name='PrometheusSG'
      body='prometheus/sg.yml'
      depends_on='vpc2017a'
      P="${P} 'ParameterKey=TrustedIPs,ParameterValue=\"${TRUSTED_IPS:-\"$(vgs_get_external_ip)/32\"}\"'"
      ;;
    puppetdb)
      export AWS_PROFILE='aws2017a'
      name='PuppetDB'
      body='puppet/db.yml'
      depends_on='vpc2017a,puppetsg'
      P="${P} 'ParameterKey=DBName,ParameterValue=${PP_DB_NAME}'"
      P="${P} 'ParameterKey=DBUser,ParameterValue=${PP_DB_USER}'"
      P="${P} 'ParameterKey=DBPassword,ParameterValue=${PP_DB_PASS}'"
      ;;
    puppetsg)
      export AWS_PROFILE='aws2017a'
      name='PuppetSG'
      body='puppet/sg.yml'
      depends_on='vpc2017a'
      P="${P} 'ParameterKey=TrustedIPs,ParameterValue=\"${TRUSTED_IPS:-\"$(vgs_get_external_ip)/32\"}\"'"
      ;;
    vgh)
      export AWS_PROFILE='default'
      name='VGH'
      body='vgh.yml'
      depends_on='prometheus-iam'
      A='--capabilities CAPABILITY_NAMED_IAM'
      P="${P} 'ParameterKey=AssetsBucketName,ParameterValue=${AWS_VGH_ASSETS_BUCKET}'"
      P="${P} 'ParameterKey=BackupBucketName,ParameterValue=${AWS_VGH_BACKUP_BUCKET}'"
      P="${P} 'ParameterKey=SecretsBucketName,ParameterValue=${AWS_VGH_SECRETS_BUCKET}'"
      P="${P} 'ParameterKey=PrometheusInstanceRoleArn,ParameterValue=\"$(AWS_PROFILE=aws2017a  vgs_aws_cfn_get_output PrometheusIAM InstanceRoleArn)\"'"
      ;;
    vpc)
      name='VPC'
      body='vpc.yml'
      P="${P} 'ParameterKey=NumberOfAZs,ParameterValue=${AWS_AZ_NUMBER}'"
      ;;
    vpc2017a)
      export AWS_PROFILE='aws2017a'
      name='VPC'
      body='vpc.yml'
      P="${P} 'ParameterKey=NumberOfAZs,ParameterValue=${AWS_AZ_NUMBER}'"
      ;;
    *)
      usage
      ;;
  esac

  export cfn_cmd="--stack-name ${name} --template-body file://${AWS_CFN_STACKS_PATH}/${body} ${A} --parameters ${P} --tags ${T}"
}

clear_cfn(){
  unset stack name body depends_on A P T cfn_cmd
}
