#!/usr/bin/env bash

# Bash strict mode
set -euo pipefail
IFS=$'\n\t'

# DEBUG
[ -z "${DEBUG:-}" ] || set -x

# System VARs
APPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')
NOW="$(date +"%Y%m%d_%H%M%S")"
VERSION=$(git --git-dir="${APPDIR}/.git" --work-tree="${APPDIR}" describe --always --tags)
export APPDIR TMPDIR NOW VERSION

# Detect environment
GIT_BRANCH="${TRAVIS_BRANCH:-$(git symbolic-ref --short HEAD)}"
if [[ -n "${ENVTYPE:-}" ]]; then
  ENVTYPE="$ENVTYPE"
elif [[ -n "${GIT_BRANCH:-}" ]]; then
  if [[ "$GIT_BRANCH" == 'master' ]]; then
    ENVTYPE='production'
  else
    ENVTYPE="$GIT_BRANCH"
  fi
else
  ENVTYPE=${ENVTYPE:-production}
fi
export ENVTYPE GIT_BRANCH

if [[ ${TRAVIS:-false} == true ]] && [[ ${TRAVIS_PULL_REQUEST:-false} == false ]]; then
  echo 'Configure AWS Credentials'
  aws configure --profile ursa set region us-east-1
  aws configure --profile ursa set aws_access_key_id "${TRAVIS_AWS_ACCESS_KEY_ID}"
  aws configure --profile ursa set aws_secret_access_key "${TRAVIS_AWS_SECRET_ACCESS_KEY}"
  aws configure --profile orion set role_arn "${TRAVIS_ORION_ROLE_ARN}"
  aws configure --profile orion set source_profile ursa
fi

# Load functions
if [[ -d "${APPDIR}/shlib" ]]; then
  # shellcheck disable=1090
  for file in "${APPDIR}"/shlib/*.sh; do . "$file"; done
fi

# Get AWS SSM Parameters
export DEPLOY_RSA
DEPLOY_RSA="$(aws ssm  --region us-east-1  --profile ursa get-parameter --name /vgh/deploy_rsa --with-decryption --query Parameter.Value --output text)"
