#!/usr/bin/env bash
# Stack CLI

# Usage
usage(){
  echo '---------------------------------------------'
  echo "USAGE: ${BASH_SOURCE[0]} [COMMAND] [OPTIONS]"
  echo '---------------------------------------------'
  echo 'Commands:'
  echo ''
  echo '  - deploy [NAME]'
  echo ''
  echo '----------------------------------------------'
  echo 'For more information please consult the README'
  echo '----------------------------------------------'
  exit 1
}

# Bash strict mode
set -euo pipefail
IFS=$'\n\t'

# Debug
[ -z "${DEBUG:-}" ] || set -x

# System VARs
NOW="$(date +"%Y%m%d_%H%M%S")"
TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')
APPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
VERSION=$(git --git-dir="${APPDIR}/.git" --work-tree="${APPDIR}" describe --always --tags)
export NOW TMPDIR APPDIR VERSION

# Output
e_ok()    { printf "  ✔  %s\\n" "$@" ;}
e_info()  { printf "  ➜  %s\\n" "$@" ;}
e_error() { printf "  ✖  %s\\n" "$@" ;}
e_warn()  { printf "    %s\\n" "$@" ;}
e_abort() { e_error "$1"; return "${2:-1}" ;}

# Deploy
deploy(){
  local stack="${1:-?Stack name is required}"

  SSH_HOST="${SSH_HOST:-?Must specify SSH_HOST}"
  SSH_USER="${SSH_USER:-ubuntu}"
  SSH_CMD="ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SSH_HOST}"

  e_info 'Deploy stack'
  case "$STACK_TYPE" in
    swarm)
      ( envsubst < "${APPDIR}/swarm/${stack}.yml" | eval "$SSH_CMD" "sudo docker stack deploy --prune --compose-file - ${stack}" )
      ;;
    compose)
      ( envsubst < "${APPDIR}/compose/${stack}.yml" | eval "$SSH_CMD" "sudo docker-compose --project-name ${stack} --file - pull" )
      ( envsubst < "${APPDIR}/compose/${stack}.yml" | eval "$SSH_CMD" "sudo docker-compose --project-name ${stack} --file - up -d --remove-orphans" )
      ;;
  esac
}

# Clean-up
clean_up() {
  if [[ "${CI:-false}" == 'true' ]]; then
    if [[ -s "${APPDIR}/.env" ]]; then
      e_info 'Removing .env'
      shred -fu "${APPDIR:?}/.env"
    fi
  fi
}

# Process CLI
process_cli(){
  trap 'clean_up' EXIT HUP INT QUIT TERM
  if [[ -z $1 ]]; then usage; fi

  local cmd stack
  cmd="${1:-}"; shift || true
  stack="${1:-}"; shift || true

  # Defaults
  SSH_USER='ansible'

  case "$stack" in
    monitor)
      SSH_HOST='prometheus.ghn.me'
      STACK_TYPE='swarm'
      ;;
    vault)
      SSH_HOST='prometheus.ghn.me'
      STACK_TYPE='compose'
      echo 'Stack not available'; exit
      ;;
    *)
      echo 'Stack name not recognized!';
      usage
      ;;
  esac

  case "$cmd" in
    deploy)
      deploy "$stack"
      ;;
    *)
      usage
      ;;
  esac
}

process_cli "${@:-}"
