#!/usr/bin/env bash
# GIT Pre-Push Hook

# Load environment
# shellcheck disable=1090
. "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)/.env.sh"

# Hooks
e_header 'GIT Pre-Push:'
e_info 'Nothing yet'

# Git Push
e_header 'GIT Push:'
e_info 'Nothing yet'
